export type ApiErrorCode =
  | 'UNAUTHENTICATED'
  | 'TENANT_MEMBERSHIP_REQUIRED'
  | 'INVALID_LOGIN_REQUEST'
  | 'INVALID_CREDENTIALS'
  | 'SESSION_CONTEXT_FAILED'
  | 'FORBIDDEN'
  | 'TENANT_PROFILE_NOT_FOUND'
  | 'INVALID_TENANT_PROFILE'
  | 'TENANT_UPDATE_FAILED'
  | 'INVALID_STAFF_REQUEST'
  | 'STAFF_EMAIL_ALREADY_EXISTS'
  | 'STAFF_CREATION_FAILED';

export type ApiErrorResponse = {
  error: {
    code: ApiErrorCode;
    message: string;
  };
};
